In [ ]:
!pip install "advertools>=0.8.1"

Collecting advertools>=0.8.1
  Downloading advertools-0.13.0-py2.py3-none-any.whl (287 kB)
     |████████████████████████████████| 287 kB 22.9 MB/s
Requirement already satisfied: pyasn1 in /usr/local/lib/python3.7/dist-packages (from advertools>=0.8.1) (0.4.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from advertools>=0.8.1) (1.3.5)
Collecting twython
  Downloading twython-3.9.1-py3-none-any.whl (33 kB)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (from advertools>=0.8.1) (6.0.1)
Collecting scrapy
  Downloading Scrapy-2.6.1-py2.py3-none-any.whl (264 kB)
     |████████████████████████████████| 264 kB 32.5 MB/s
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->advertools>=0.8.1) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->advertools>=0.8.1) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->advertools>=0.8.1) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->advertools>=0.8.1) (1.15.0)
Collecting Twisted>=17.9.0
  Downloading Twisted-22.4.0-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 29.4 MB/s
Requirement already satisfied: lxml>=3.5.0 in /usr/local/lib/python3.7/dist-packages (from scrapy->advertools>=0.8.1) (4.2.6)
Collecting protego>=0.1.15
  Downloading Protego-0.2.1-py2.py3-none-any.whl (8.2 kB)
Collecting PyDispatcher>=2.0.5
  Downloading PyDispatcher-2.0.5.zip (47 kB)
     |████████████████████████████████| 47 kB 4.0 MB/s
Collecting itemloaders>=1.0.1
  Downloading itemloaders-1.0.4-py3-none-any.whl (11 kB)
Collecting zope.interface>=4.1.3
  Downloading zope.interface-5.4.0-cp37-cp37m-manylinux2010_x86_64.whl (251 kB)
     |████████████████████████████████| 251 kB 47.3 MB/s
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from scrapy->advertools>=0.8.1) (57.4.0)
Collecting w3lib>=1.17.0
  Downloading w3lib-1.22.0-py2.py3-none-any.whl (20 kB)
Collecting service-identity>=16.0.0
  Downloading service_identity-21.1.0-py2.py3-none-any.whl (12 kB)
Collecting parsel>=1.5.0
  Downloading parsel-1.6.0-py2.py3-none-any.whl (13 kB)
Collecting cssselect>=0.9.1
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting pyOpenSSL>=16.2.0
  Downloading pyOpenSSL-22.0.0-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 3.7 MB/s
Collecting itemadapter>=0.1.0
  Downloading itemadapter-0.5.0-py3-none-any.whl (10 kB)
Collecting tldextract
  Downloading tldextract-3.3.0-py3-none-any.whl (93 kB)
     |████████████████████████████████| 93 kB 2.0 MB/s
Collecting queuelib>=1.4.2
  Downloading queuelib-1.6.2-py2.py3-none-any.whl (13 kB)
Collecting cryptography>=2.0
  Downloading cryptography-37.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 45.6 MB/s
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=2.0->scrapy->advertools>=0.8.1) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=2.0->scrapy->advertools>=0.8.1) (2.21)
Collecting jmespath>=0.9.5
  Downloading jmespath-1.0.0-py3-none-any.whl (23 kB)
Requirement already satisfied: pyasn1-modules in /usr/local/lib/python3.7/dist-packages (from service-identity>=16.0.0->scrapy->advertools>=0.8.1) (0.2.8)
Requirement already satisfied: attrs>=19.1.0 in /usr/local/lib/python3.7/dist-packages (from service-identity>=16.0.0->scrapy->advertools>=0.8.1) (21.4.0)
Collecting Automat>=0.8.0
  Downloading Automat-20.2.0-py2.py3-none-any.whl (31 kB)
Collecting incremental>=21.3.0
  Downloading incremental-21.3.0-py2.py3-none-any.whl (15 kB)
Collecting constantly>=15.1
  Downloading constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting hyperlink>=17.1.1
  Downloading hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
     |████████████████████████████████| 74 kB 2.7 MB/s
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.7/dist-packages (from Twisted>=17.9.0->scrapy->advertools>=0.8.1) (4.2.0)
Requirement already satisfied: idna>=2.5 in /usr/local/lib/python3.7/dist-packages (from hyperlink>=17.1.1->Twisted>=17.9.0->scrapy->advertools>=0.8.1) (2.10)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.7/dist-packages (from tldextract->scrapy->advertools>=0.8.1) (3.6.0)
Collecting requests-file>=1.4
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: requests>=2.1.0 in /usr/local/lib/python3.7/dist-packages (from tldextract->scrapy->advertools>=0.8.1) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->tldextract->scrapy->advertools>=0.8.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->tldextract->scrapy->advertools>=0.8.1) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->tldextract->scrapy->advertools>=0.8.1) (1.24.3)
Requirement already satisfied: requests-oauthlib>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from twython->advertools>=0.8.1) (1.3.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.4.0->twython->advertools>=0.8.1) (3.2.0)
Building wheels for collected packages: PyDispatcher
  Building wheel for PyDispatcher (setup.py) ... done
  Created wheel for PyDispatcher: filename=PyDispatcher-2.0.5-py3-none-any.whl size=11516 sha256=ef16e05e38f77cde6a4224e493c06ebb32cc1449bb6718cb567731f0b7d8c8d7
  Stored in directory: /root/.cache/pip/wheels/2d/18/21/3c6a732eaa69a339198e08bb63b7da2c45933a3428b29ec454
Successfully built PyDispatcher
Installing collected packages: w3lib, cssselect, zope.interface, requests-file, parsel, jmespath, itemadapter, incremental, hyperlink, cryptography, constantly, Automat, Twisted, tldextract, service-identity, queuelib, pyOpenSSL, PyDispatcher, protego, itemloaders, twython, scrapy, advertools
Successfully installed Automat-20.2.0 PyDispatcher-2.0.5 Twisted-22.4.0 advertools-0.13.0 constantly-15.1.0 cryptography-37.0.2 cssselect-1.1.0 hyperlink-21.0.0 incremental-21.3.0 itemadapter-0.5.0 itemloaders-1.0.4 jmespath-1.0.0 parsel-1.6.0 protego-0.2.1 pyOpenSSL-22.0.0 queuelib-1.6.2 requests-file-1.5.1 scrapy-2.6.1 service-identity-21.1.0 tldextract-3.3.0 twython-3.9.1 w3lib-1.22.0 zope.interface-5.4.0

In [ ]:
import datetime

import advertools as adv
import pandas as pd
import plotly.graph_objects as go
import plotly


key = 'Enter Youtube Data API key'
pd.options.display.max_columns = None

print('package    version')
print('==================')
for package in [adv,pd, plotly]:
    print(f'{package.__name__:<12}', package.__version__)
print('\nLast updated:', format(datetime.datetime.now(), '%b %d, %Y'))

package    version
==================
advertools   0.13.0
pandas       1.3.5
plotly       5.5.0

Last updated: May 05, 2022

In [ ]:
list(enumerate([func for func in dir(adv.youtube) if func[0] != '_'], 1))

[(1, 'activities_list'),
 (2, 'captions_list'),
 (3, 'channel_sections_list'),
 (4, 'channels_list'),
 (5, 'comment_threads_list'),
 (6, 'comments_list'),
 (7, 'guide_categories_list'),
 (8, 'i18n_languages_list'),
 (9, 'i18n_regions_list'),
 (10, 'playlist_items_list'),
 (11, 'playlists_list'),
 (12, 'search'),
 (13, 'subscriptions_list'),
 (14, 'video_categories_list'),
 (15, 'videos_list')]

In [ ]:
activities = adv.youtube.activities_list(key=key, part='snippet', channelId='UCBR8-60-B28hp2BmDPdntcQ') # see below how you can get an account's ID

In [ ]:
#activities
activities = adv.youtube.activities_list(key=key, part='snippet', channelId='UCBR8-60-B28hp2BmDPdntcQ') # see below how you can get an account's ID

In [ ]:

print(activities.shape)
activities

(5, 32)

,kind,etag,id,snippet.publishedAt,snippet.channelId,snippet.title,snippet.description,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,snippet.thumbnails.medium.url,snippet.thumbnails.medium.width,snippet.thumbnails.medium.height,snippet.thumbnails.high.url,snippet.thumbnails.high.width,snippet.thumbnails.high.height,snippet.thumbnails.standard.url,snippet.thumbnails.standard.width,snippet.thumbnails.standard.height,snippet.thumbnails.maxres.url,snippet.thumbnails.maxres.width,snippet.thumbnails.maxres.height,snippet.channelTitle,snippet.type,nextPageToken,totalResults,resultsPerPage,param_part,param_channelId,param_maxResults,param_pageToken,queryTime
0,youtube#activityListResponse,P2OgX8gHLi-j-VK2W6OZN5DQVhk,MTUxNjUwODQ2NzAwMTY1MDg0NjcwMDAwMDI0Ng,2022-04-25 00:31:40+00:00,UCBR8-60-B28hp2BmDPdntcQ,Chelsea Cutler fangirls over Doja Cat 💗 #coach...,@Chelsea Cutler sends some love to @Doja Cat a...,https://i.ytimg.com/vi/dIaxjQ4FFBo/default.jpg,120,90,https://i.ytimg.com/vi/dIaxjQ4FFBo/mqdefault.jpg,320,180,https://i.ytimg.com/vi/dIaxjQ4FFBo/hqdefault.jpg,480,360,https://i.ytimg.com/vi/dIaxjQ4FFBo/sddefault.jpg,640.0,480.0,https://i.ytimg.com/vi/dIaxjQ4FFBo/maxresdefau...,1280.0,720.0,YouTube,upload,CAUQAA,20,5,snippet,UCBR8-60-B28hp2BmDPdntcQ,None,None,2022-05-05 22:40:48.050236+00:00
1,youtube#activityListResponse,P2OgX8gHLi-j-VK2W6OZN5DQVhk,MTUxNjUwODQ2NjMxMTY1MDg0NjYzMTAwMDI2NQ,2022-04-25 00:30:31+00:00,UCBR8-60-B28hp2BmDPdntcQ,which Pink Sweat$ fact is a lie 👀 #coachella,@Pink Sweats shares two truths and a lie at Co...,https://i.ytimg.com/vi/bHnDSEG7BbM/default.jpg,120,90,https://i.ytimg.com/vi/bHnDSEG7BbM/mqdefault.jpg,320,180,https://i.ytimg.com/vi/bHnDSEG7BbM/hqdefault.jpg,480,360,NaN,NaN,NaN,NaN,NaN,NaN,YouTube,upload,CAUQAA,20,5,snippet,UCBR8-60-B28hp2BmDPdntcQ,None,None,2022-05-05 22:40:48.050236+00:00
2,youtube#activityListResponse,P2OgX8gHLi-j-VK2W6OZN5DQVhk,MTUxNjUwODQ2NTk0MTY1MDg0NjU5NDAwMDI1Ng,2022-04-25 00:29:54+00:00,UCBR8-60-B28hp2BmDPdntcQ,which isn't one of girl in red's talents 🤔 #co...,@girl in red shares two facts and a lie at Coa...,https://i.ytimg.com/vi/BRcmih7G_LM/default.jpg,120,90,https://i.ytimg.com/vi/BRcmih7G_LM/mqdefault.jpg,320,180,https://i.ytimg.com/vi/BRcmih7G_LM/hqdefault.jpg,480,360,NaN,NaN,NaN,NaN,NaN,NaN,YouTube,upload,CAUQAA,20,5,snippet,UCBR8-60-B28hp2BmDPdntcQ,None,None,2022-05-05 22:40:48.050236+00:00
3,youtube#activityListResponse,P2OgX8gHLi-j-VK2W6OZN5DQVhk,MTUxNjUwODQ2NTc1MTY1MDg0NjU3NTAwMDAzOQ,2022-04-25 00:29:35+00:00,UCBR8-60-B28hp2BmDPdntcQ,warming up with beabadoobee at #coachella 🌴,@Beabadoobee shares her pre-show routine at Co...,https://i.ytimg.com/vi/5xAoCVn_irw/default.jpg,120,90,https://i.ytimg.com/vi/5xAoCVn_irw/mqdefault.jpg,320,180,https://i.ytimg.com/vi/5xAoCVn_irw/hqdefault.jpg,480,360,NaN,NaN,NaN,NaN,NaN,NaN,YouTube,upload,CAUQAA,20,5,snippet,UCBR8-60-B28hp2BmDPdntcQ,None,None,2022-05-05 22:40:48.050236+00:00
4,youtube#activityListResponse,P2OgX8gHLi-j-VK2W6OZN5DQVhk,MTUxNjUwODQ2NTUxMTY1MDg0NjU1MTAwMDY1Mw,2022-04-25 00:29:11+00:00,UCBR8-60-B28hp2BmDPdntcQ,~relaxin~ with TOKiMONSTA at #coachella 😌,@TOKiMONSTA shares her pre-show ritual at Coac...,https://i.ytimg.com/vi/6ZIk3R8dft8/default.jpg,120,90,https://i.ytimg.com/vi/6ZIk3R8dft8/mqdefault.jpg,320,180,https://i.ytimg.com/vi/6ZIk3R8dft8/hqdefault.jpg,480,360,NaN,NaN,NaN,NaN,NaN,NaN,YouTube,upload,CAUQAA,20,5,snippet,UCBR8-60-B28hp2BmDPdntcQ,None,None,2022-05-05 22:40:48.050236+00:00

In [ ]:
activities[['snippet.channelTitle', 'snippet.publishedAt', 'snippet.type', 'snippet.title']]

,snippet.channelTitle,snippet.publishedAt,snippet.type,snippet.title
0,YouTube,2022-04-25 00:31:40+00:00,upload,Chelsea Cutler fangirls over Doja Cat 💗 #coach...
1,YouTube,2022-04-25 00:30:31+00:00,upload,which Pink Sweat$ fact is a lie 👀 #coachella
2,YouTube,2022-04-25 00:29:54+00:00,upload,which isn't one of girl in red's talents 🤔 #co...
3,YouTube,2022-04-25 00:29:35+00:00,upload,warming up with beabadoobee at #coachella 🌴
4,YouTube,2022-04-25 00:29:11+00:00,upload,~relaxin~ with TOKiMONSTA at #coachella 😌

In [ ]:
activities.filter(regex='param_')

  param_part           param_channelId param_maxResults param_pageToken
0    snippet  UCBR8-60-B28hp2BmDPdntcQ             None            None
1    snippet  UCBR8-60-B28hp2BmDPdntcQ             None            None
2    snippet  UCBR8-60-B28hp2BmDPdntcQ             None            None
3    snippet  UCBR8-60-B28hp2BmDPdntcQ             None            None
4    snippet  UCBR8-60-B28hp2BmDPdntcQ             None            None

In [ ]:
yt_channels = adv.youtube.channels_list(key=key, part='snippet,statistics,contentDetails',
                                      forUsername=['google', 'youtube', 'vevo'])
print(yt_channels.shape)
yt_channels

(3, 33)

,kind,etag,id,snippet.title,snippet.description,snippet.customUrl,snippet.publishedAt,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,snippet.thumbnails.medium.url,snippet.thumbnails.medium.width,snippet.thumbnails.medium.height,snippet.thumbnails.high.url,snippet.thumbnails.high.width,snippet.thumbnails.high.height,snippet.localized.title,snippet.localized.description,contentDetails.relatedPlaylists.likes,contentDetails.relatedPlaylists.uploads,statistics.viewCount,statistics.subscriberCount,statistics.hiddenSubscriberCount,statistics.videoCount,totalResults,resultsPerPage,param_part,param_forUsername,param_maxResults,param_pageToken,queryTime,snippet.country,snippet.defaultLanguage
0,youtube#channelListResponse,K8bzURkrR3kPhQPt0tZ70J4UatE,UCK8sQmJBp8GCxrOtXWBpyEA,Google,Experience the world of Google on our official...,google,2005-09-18 22:37:10+00:00,https://yt3.ggpht.com/ytc/AKedOLR14FbEI5TPYKnD...,88,88,https://yt3.ggpht.com/ytc/AKedOLR14FbEI5TPYKnD...,240,240,https://yt3.ggpht.com/ytc/AKedOLR14FbEI5TPYKnD...,800,800,Google,Experience the world of Google on our official...,,UUK8sQmJBp8GCxrOtXWBpyEA,3339328185,10400000,0,2576,1,5,"snippet,statistics,contentDetails",google,None,None,2022-05-05 22:53:19.924987+00:00,NaN,NaN
1,youtube#channelListResponse,Z7poE0AsN6dcXAO0iar0Tg-rMog,UCBR8-60-B28hp2BmDPdntcQ,YouTube,YouTube's Official Channel helps you discover ...,youtube,1970-01-01 00:00:00+00:00,https://yt3.ggpht.com/584JjRp5QMuKbyduM_2k5RlX...,88,88,https://yt3.ggpht.com/584JjRp5QMuKbyduM_2k5RlX...,240,240,https://yt3.ggpht.com/584JjRp5QMuKbyduM_2k5RlX...,800,800,YouTube,YouTube's Official Channel helps you discover ...,,UUBR8-60-B28hp2BmDPdntcQ,2657568488,33000000,0,492,1,5,"snippet,statistics,contentDetails",youtube,None,None,2022-05-05 22:53:20.066207+00:00,US,NaN
2,youtube#channelListResponse,-sMdWSl9Ltrie0zWWAgAcjGxEOs,UC2pmfLm7iq6Ov1UwYrWYkZA,Vevo,"Vevo on YouTube - Official Music Videos, Live ...",vevo,2006-04-14 17:07:29+00:00,https://yt3.ggpht.com/ytc/AKedOLTSxnTNlW-ES1fh...,88,88,https://yt3.ggpht.com/ytc/AKedOLTSxnTNlW-ES1fh...,240,240,https://yt3.ggpht.com/ytc/AKedOLTSxnTNlW-ES1fh...,800,800,Vevo,"Vevo on YouTube - Official Music Videos, Live ...",,UU2pmfLm7iq6Ov1UwYrWYkZA,541863605,20000000,0,1447,1,5,"snippet,statistics,contentDetails",vevo,None,None,2022-05-05 22:53:20.211167+00:00,NaN,en

In [ ]:
yt_channels.filter(regex='snippet\.title|statistics|query|published').set_index(['queryTime', 'snippet.publishedAt', 'snippet.title']).style.format('{:,}')

In [ ]:
yt_channels.filter(regex='content')

,contentDetails.relatedPlaylists.likes,contentDetails.relatedPlaylists.uploads
0,,UUK8sQmJBp8GCxrOtXWBpyEA
1,,UUBR8-60-B28hp2BmDPdntcQ
2,,UU2pmfLm7iq6Ov1UwYrWYkZA

In [ ]:
channels_activities = adv.youtube.activities_list(key=key, part='contentDetails,snippet',
                                                   channelId=yt_channels['id'].tolist(), maxResults=200) 
#channels_activities = pd.read_csv('channels_activities.csv', parse_dates=['snippet.publishedAt'])
print(channels_activities.shape)
channels_activities.head(3)

(316, 37)

,kind,etag,id,snippet.publishedAt,snippet.channelId,snippet.title,snippet.description,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,snippet.thumbnails.medium.url,snippet.thumbnails.medium.width,snippet.thumbnails.medium.height,snippet.thumbnails.high.url,snippet.thumbnails.high.width,snippet.thumbnails.high.height,snippet.channelTitle,snippet.type,contentDetails.upload.videoId,snippet.thumbnails.standard.url,snippet.thumbnails.standard.width,snippet.thumbnails.standard.height,snippet.thumbnails.maxres.url,snippet.thumbnails.maxres.width,snippet.thumbnails.maxres.height,snippet.groupId,nextPageToken,totalResults,resultsPerPage,param_part,param_channelId,param_maxResults,param_pageToken,queryTime,prevPageToken,contentDetails.subscription.resourceId.kind,contentDetails.subscription.resourceId.channelId
0,youtube#activityListResponse,Pqz4W0DIjrkLJxurmQsrEvQ1uvQ,MTUxNjUxNjgzNjQ1MTY1MTY4MzY0NTAwMDQ2MQ,2022-05-04 17:00:45+00:00,UCK8sQmJBp8GCxrOtXWBpyEA,Andra Day | Watch With Me | Google TV,What does your watchlist say about you? In our...,https://i.ytimg.com/vi/siGvwZIL_gA/default.jpg,120.0,90.0,https://i.ytimg.com/vi/siGvwZIL_gA/mqdefault.jpg,320.0,180.0,https://i.ytimg.com/vi/siGvwZIL_gA/hqdefault.jpg,480.0,360.0,Google,upload,siGvwZIL_gA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CDIQAA,110,50,"contentDetails,snippet",UCK8sQmJBp8GCxrOtXWBpyEA,50,None,2022-05-05 22:53:27.723758+00:00,NaN,NaN,NaN
1,youtube#activityListResponse,Pqz4W0DIjrkLJxurmQsrEvQ1uvQ,MTUxNjUxNjgzNjQyMTY1MTY4MzY0MjAwMDUyMg,2022-05-04 17:00:42+00:00,UCK8sQmJBp8GCxrOtXWBpyEA,Andra Day | Watch With Me | Google TV | Behind...,What does your watchlist say about you? In our...,https://i.ytimg.com/vi/SZl_XJYsTIY/default.jpg,120.0,90.0,https://i.ytimg.com/vi/SZl_XJYsTIY/mqdefault.jpg,320.0,180.0,https://i.ytimg.com/vi/SZl_XJYsTIY/hqdefault.jpg,480.0,360.0,Google,upload,SZl_XJYsTIY,https://i.ytimg.com/vi/SZl_XJYsTIY/sddefault.jpg,640.0,480.0,https://i.ytimg.com/vi/SZl_XJYsTIY/maxresdefau...,1280.0,720.0,NaN,CDIQAA,110,50,"contentDetails,snippet",UCK8sQmJBp8GCxrOtXWBpyEA,50,None,2022-05-05 22:53:27.723758+00:00,NaN,NaN,NaN
2,youtube#activityListResponse,Pqz4W0DIjrkLJxurmQsrEvQ1uvQ,MTUxNjUxNjgzNjQwMTY1MTY4MzY0MDAwMDI1Ng,2022-05-04 17:00:40+00:00,UCK8sQmJBp8GCxrOtXWBpyEA,Andra Day | Watch With Me | Google TV | Veneno,What does your watchlist say about you? In our...,https://i.ytimg.com/vi/U7g7KVdaHYQ/default.jpg,120.0,90.0,https://i.ytimg.com/vi/U7g7KVdaHYQ/mqdefault.jpg,320.0,180.0,https://i.ytimg.com/vi/U7g7KVdaHYQ/hqdefault.jpg,480.0,360.0,Google,upload,U7g7KVdaHYQ,https://i.ytimg.com/vi/U7g7KVdaHYQ/sddefault.jpg,640.0,480.0,https://i.ytimg.com/vi/U7g7KVdaHYQ/maxresdefau...,1280.0,720.0,NaN,CDIQAA,110,50,"contentDetails,snippet",UCK8sQmJBp8GCxrOtXWBpyEA,50,None,2022-05-05 22:53:27.723758+00:00,NaN,NaN,NaN

In [ ]:
channels_activities.groupby('snippet.channelTitle')['snippet.type'].value_counts().to_frame()

                                   snippet.type
snippet.channelTitle snippet.type
Alesso               subscription             1
AltOnVEVO            subscription             1
Ann Marie            subscription             1
Ari Lennox           subscription             1
Axwell Λ Ingrosso    subscription             1
...                                         ...
X Ambassadors        subscription             1
YouTube              upload                 101
Zara Larsson         subscription             1
countryVEVO          subscription             1
nicki nicole         subscription             1

[91 rows x 1 columns]

In [ ]:
channels_activities['pub_month'] = [pd.Period(p, 'M') for p in channels_activities['snippet.publishedAt']]
channels_activities['pub_year'] = [pd.Period(p, 'A') for p in channels_activities['snippet.publishedAt']]
channels_activities.filter(regex='pub').head()

        snippet.publishedAt pub_month pub_year
0 2022-05-04 17:00:45+00:00   2022-05     2022
1 2022-05-04 17:00:42+00:00   2022-05     2022
2 2022-05-04 17:00:40+00:00   2022-05     2022
3 2022-05-04 17:00:37+00:00   2022-05     2022
4 2022-04-18 22:11:12+00:00   2022-04     2022

In [ ]:
channels_activities['snippet.channelTitle'].unique()

array(['Google', 'YouTube', 'Vevo', 'Reik', 'Greeicy', 'Luísa Sonza',
       'CNCO', 'Mau y Ricky', 'Wisin', 'Luis Fonsi', 'GLORIA TREVI',
       'Jossef', 'Ricky Martin', 'Beéle', 'Ann Marie', 'Kiana Ledé',
       'Ari Lennox', 'Jacquees', 'Queen Naija', 'Sevyn Streeter',
       'Sleepy Hallow', 'Chlöe', 'Migos ATL', 'Clinton Kane',
       'Mae Muller', 'JID', 'M24 OFFICIAL', 'Meghan Trainor',
       'BoyWithUke', 'SwitchOTR', 'BASTILLEvideos', 'Denzel Curry',
       'George Harrison', 'Grimes', 'Genesis Owusu', 'Axwell Λ Ingrosso',
       'Alesso', 'DJ Snake', 'Latto', 'The Chainsmokers', 'Bobby Shmurda',
       'Zara Larsson', 'Kane Brown', 'SZA', 'Jhené Aiko', 'G-Eazy',
       'Calibre50', 'MoneyBagg Yo', 'Mariah Angeliq', 'Huddy', 'Tainy',
       'French Montana', 'X Ambassadors', 'Tom Odell', 'Calum Scott',
       'Conan Gray', 'Jeremy Zucker', 'SAM SMITH', 'nicki nicole',
       'Lewis Capaldi', 'Coi Leray', 'ROSALÍA', 'James Arthur',
       'Tiwa Savage', 'StarBoy TV', 'Davido', 'Original Koffee',
       'Shenseea', 'Jonas Brothers', 'Marshmello', 'Camila Cabello',
       'Harry Styles', 'Elton John', 'Troye Sivan', 'Dean Lewis', 'BENEE',
       'Bryson Tiller', 'Summer Walker', 'Normani', 'KALI UCHIS',
       'Maluma', 'TINI', 'Sebastián Yatra', 'Camilo', 'Farruko',
       'AltOnVEVO', 'countryVEVO', 'JazzOnVEVO', 'ClassicalMusicVEVO',
       'Vevo France', 'Vevo Polska'], dtype=object)

In [ ]:
fig = go.Figure()
for channel in ['YouTube', 'Google', 'Vevo']:
    df = (channels_activities
          [(channels_activities['snippet.channelTitle']==channel) & (channels_activities['snippet.type']=='upload')]
          .groupby(['pub_month', 'snippet.channelTitle'])
          ['snippet.type']
          .value_counts().to_frame()
          .rename(columns={'snippet.type': 'count'})
          .reset_index())
    fig.add_scatter(x=df['pub_month'].astype(str), y=df['count'], name=channel, mode='lines+markers', marker={'size': 10})

fig.layout.template = 'none'
fig.layout.title = 'Video Uploads per Month'
fig

In [ ]:
fig = go.Figure()
for channel in ['YouTube', 'Google', 'Vevo']:
    df = (channels_activities
          [(channels_activities['snippet.channelTitle']==channel) & (channels_activities['snippet.type']=='upload')]
          .groupby(['pub_year', 'snippet.channelTitle'])
          ['snippet.type']
          .value_counts().to_frame()
          .rename(columns={'snippet.type': 'count'})
          .reset_index())
    fig.add_scatter(x=df['pub_year'].astype(str), y=df['count'], name=channel, marker={'size': 10})

fig.layout.template = 'none'
fig.layout.title = 'Video Uploads per Year'
fig

In [ ]:
for channel in channels_activities['snippet.channelTitle'].unique():
    channel_df = channels_activities[channels_activities['snippet.channelTitle']==channel]
    val_counts = (channel_df['snippet.type'].value_counts()
                  .rename_axis(channel, axis=0))
    dates = channel_df['snippet.publishedAt']
    print(val_counts)
    print(' min date: ', dates.min().date(), ' | max date: ', dates.max().date(), ' | time delta: ', dates.max() - dates.min(), sep='')
    print('====\n')

Google
upload    106
Name: snippet.type, dtype: int64
 min date: 2021-10-06 | max date: 2022-05-04 | time delta: 210 days 09:55:59
====

YouTube
upload    101
Name: snippet.type, dtype: int64
 min date: 2021-09-07 | max date: 2022-04-25 | time delta: 229 days 05:30:48
====

Vevo
upload    21
Name: snippet.type, dtype: int64
 min date: 2022-01-22 | max date: 2022-04-30 | time delta: 97 days 22:59:50
====

Reik
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Greeicy
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Luísa Sonza
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

CNCO
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Mau y Ricky
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Wisin
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Luis Fonsi
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

GLORIA TREVI
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Jossef
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Ricky Martin
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Beéle
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Ann Marie
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Kiana Ledé
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Ari Lennox
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Jacquees
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Queen Naija
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Sevyn Streeter
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Sleepy Hallow
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Chlöe
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Migos ATL
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Clinton Kane
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Mae Muller
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

JID
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

M24 OFFICIAL
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Meghan Trainor
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

BoyWithUke
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

SwitchOTR
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

BASTILLEvideos
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Denzel Curry
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

George Harrison
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Grimes
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Genesis Owusu
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-02-05 | max date: 2022-02-05 | time delta: 0 days 00:00:00
====

Axwell Λ Ingrosso
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Alesso
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

DJ Snake
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Latto
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

The Chainsmokers
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Bobby Shmurda
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Zara Larsson
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Kane Brown
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

SZA
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Jhené Aiko
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

G-Eazy
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Calibre50
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

MoneyBagg Yo
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Mariah Angeliq
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Huddy
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Tainy
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

French Montana
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

X Ambassadors
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Tom Odell
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Calum Scott
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Conan Gray
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Jeremy Zucker
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

SAM SMITH
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

nicki nicole
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Lewis Capaldi
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Coi Leray
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

ROSALÍA
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

James Arthur
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Tiwa Savage
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

StarBoy TV
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Davido
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Original Koffee
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Shenseea
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Jonas Brothers
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Marshmello
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Camila Cabello
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Harry Styles
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Elton John
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Troye Sivan
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Dean Lewis
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

BENEE
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Bryson Tiller
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Summer Walker
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Normani
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

KALI UCHIS
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Maluma
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

TINI
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Sebastián Yatra
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Camilo
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Farruko
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

AltOnVEVO
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

countryVEVO
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

JazzOnVEVO
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

ClassicalMusicVEVO
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Vevo France
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

Vevo Polska
subscription    1
Name: snippet.type, dtype: int64
 min date: 2022-01-02 | max date: 2022-01-02 | time delta: 0 days 00:00:00
====

In [ ]:
languages = adv.youtube.i18n_languages_list(key=key, part='snippet', hl=['en', 'fr', 'de'])
#languages = pd.read_csv('languages.csv', parse_dates=['queryTime'])
languages.head()

,kind,etag,id,snippet.hl,snippet.name,param_part,param_hl,param_maxResults,param_pageToken,queryTime
0,youtube#i18nLanguageListResponse,BWfamz4EkEUnBLn4e5RPGocAZbo,af,af,Afrikaans,snippet,en,None,None,2022-05-05 22:53:58.291481+00:00
1,youtube#i18nLanguageListResponse,BWfamz4EkEUnBLn4e5RPGocAZbo,am,am,Amharic,snippet,en,None,None,2022-05-05 22:53:58.291481+00:00
2,youtube#i18nLanguageListResponse,BWfamz4EkEUnBLn4e5RPGocAZbo,ar,ar,Arabic,snippet,en,None,None,2022-05-05 22:53:58.291481+00:00
3,youtube#i18nLanguageListResponse,BWfamz4EkEUnBLn4e5RPGocAZbo,as,as,Assamese,snippet,en,None,None,2022-05-05 22:53:58.291481+00:00
4,youtube#i18nLanguageListResponse,BWfamz4EkEUnBLn4e5RPGocAZbo,az,az,Azerbaijani,snippet,en,None,None,2022-05-05 22:53:58.291481+00:00

In [ ]:
(languages
 .filter(regex='id|name|param_hl')
 .sort_values('id')[:12]
 .reset_index(drop=True))

    id snippet.name param_hl
0   af    Afrikaans       en
1   af    Afrikaans       de
2   af    Afrikaans       fr
3   am      Amharic       en
4   am    Amharisch       de
5   am    Amharique       fr
6   ar       Arabic       en
7   ar     Arabisch       de
8   ar        Arabe       fr
9   as  Assamesisch       de
10  as     Assamais       fr
11  as     Assamese       en

In [ ]:
regions = adv.youtube.i18n_regions_list(key=key, part='snippet', hl=['en', 'ar', 'ja'])
#regions = pd.read_csv('regions.csv', parse_dates=['queryTime'])
#regions.head()

In [ ]:
(regions
 .filter(regex='id|name|param_hl')
 .sort_values('id')[:12]
 .reset_index(drop=True))

    id              snippet.name param_hl
0   AE      United Arab Emirates       en
1   AE                  アラブ首長国連邦       ja
2   AE  الإمارات العربية المتحدة       ar
3   AR                 الأرجنتين       ar
4   AR                 Argentina       en
5   AR                    アルゼンチン       ja
6   AT                    النمسا       ar
7   AT                   Austria       en
8   AT                    オーストリア       ja
9   AU                 Australia       en
10  AU                   オーストラリア       ja
11  AU                  أستراليا       ar

In [ ]:
#channel_categories = adv.youtube.guide_categories_list(key = key, part = 'snippet')
channel_categories = pd.read_csv('channel_categories.csv', parse_dates=['queryTime'])
channel_categories.head(3)

,kind,etag,id,snippet.channelId,snippet.title,param_part,param_regionCode,param_maxResults,param_pageToken,queryTime
0,youtube#guideCategoryListResponse,"""Fznwjl6JEQdo1MGvHOGaz_YanRU/cKe5cQFDAFacJgSsR...",GCQmVzdCBvZiBZb3VUdWJl,UCBR8-60-B28hp2BmDPdntcQ,Best of YouTube,snippet,us,NaN,NaN,2020-02-04 13:22:31.112049+00:00
1,youtube#guideCategoryListResponse,"""Fznwjl6JEQdo1MGvHOGaz_YanRU/cKe5cQFDAFacJgSsR...",GCQ3JlYXRvciBvbiB0aGUgUmlzZQ,UCBR8-60-B28hp2BmDPdntcQ,Creator on the Rise,snippet,us,NaN,NaN,2020-02-04 13:22:31.112049+00:00
2,youtube#guideCategoryListResponse,"""Fznwjl6JEQdo1MGvHOGaz_YanRU/cKe5cQFDAFacJgSsR...",GCTXVzaWM,UCBR8-60-B28hp2BmDPdntcQ,Music,snippet,us,NaN,NaN,2020-02-04 13:22:31.112049+00:00

In [ ]:
channel_categories['snippet.title'].to_frame()

           snippet.title
0        Best of YouTube
1    Creator on the Rise
2                  Music
3                 Comedy
4   Film & Entertainment
5                 Gaming
6       Beauty & Fashion
7                 Sports
8                   Tech
9       Cooking & Health
10       News & Politics

In [ ]:
video_categories = adv.youtube.video_categories_list(key=key, part='snippet', regionCode='us', hl=['en', 'es', 'zh-CN'])
video_categories.head(3)

,kind,etag,id,snippet.title,snippet.assignable,snippet.channelId,param_part,param_regionCode,param_hl,param_maxResults,param_pageToken,queryTime
0,youtube#videoCategoryListResponse,QteLrrS_X7rM7rlcU_e7qa0embQ,1,Film & Animation,True,UCBR8-60-B28hp2BmDPdntcQ,snippet,us,en,None,None,2022-05-05 22:54:17.244845+00:00
1,youtube#videoCategoryListResponse,QteLrrS_X7rM7rlcU_e7qa0embQ,2,Autos & Vehicles,True,UCBR8-60-B28hp2BmDPdntcQ,snippet,us,en,None,None,2022-05-05 22:54:17.244845+00:00
2,youtube#videoCategoryListResponse,QteLrrS_X7rM7rlcU_e7qa0embQ,10,Music,True,UCBR8-60-B28hp2BmDPdntcQ,snippet,us,en,None,None,2022-05-05 22:54:17.244845+00:00

In [ ]:
(video_categories
 .iloc[pd.Series([(x,x+32,x+64) for x in range(32)]).explode()]
 [['id', 'snippet.title', 'param_hl']]
 [:15])

    id        snippet.title param_hl
0    1     Film & Animation       en
32   1     Cine y animación       es
64   1                电影和动画    zh-CN
1    2     Autos & Vehicles       en
33   2                Motor       es
65   2                   汽车    zh-CN
2   10                Music       en
34  10               Música       es
66  10                   音乐    zh-CN
3   15       Pets & Animals       en
35  15  Mascotas y animales       es
67  15                宠物和动物    zh-CN
4   17               Sports       en
36  17             Deportes       es
68  17                   体育    zh-CN

In [ ]:
comment_thrd_vid = adv.youtube.comment_threads_list(key=key, part='snippet', videoId='kJQP7kiw5Fk',
                                                     maxResults=150,)

comment_thrd_vid.head(3)

,kind,etag,id,snippet.videoId,snippet.topLevelComment.kind,snippet.topLevelComment.etag,snippet.topLevelComment.id,snippet.topLevelComment.snippet.videoId,snippet.topLevelComment.snippet.textDisplay,snippet.topLevelComment.snippet.textOriginal,snippet.topLevelComment.snippet.authorDisplayName,snippet.topLevelComment.snippet.authorProfileImageUrl,snippet.topLevelComment.snippet.authorChannelUrl,snippet.topLevelComment.snippet.authorChannelId.value,snippet.topLevelComment.snippet.canRate,snippet.topLevelComment.snippet.viewerRating,snippet.topLevelComment.snippet.likeCount,snippet.topLevelComment.snippet.publishedAt,snippet.topLevelComment.snippet.updatedAt,snippet.canReply,snippet.totalReplyCount,snippet.isPublic,nextPageToken,totalResults,resultsPerPage,param_part,param_videoId,param_maxResults,param_pageToken,queryTime
0,youtube#commentThreadListResponse,TDvBXUAZ9rIcMc4DRhJ8ZhjjG6I,UgzKkFDLaMSNZ2IED6J4AaABAg,kJQP7kiw5Fk,youtube#comment,DITvh-st1rE5soLQN6lqLS-ALkc,UgzKkFDLaMSNZ2IED6J4AaABAg,kJQP7kiw5Fk,💋💋💋💋💋💋,💋💋💋💋💋💋,Renàta Németh,https://yt3.ggpht.com/ytc/AKedOLRZHIxt5TPwc2ol...,http://www.youtube.com/channel/UC310yReVLuaLKt...,UC310yReVLuaLKtizh-aRwcQ,True,none,0,2022-05-05 22:49:25+00:00,2022-05-05 22:49:25+00:00,True,0,True,QURTSl9pM2ctV1F1VHV2dmJ0VUtrbHdIWG5PVUJjeHVkNk...,90,100,snippet,kJQP7kiw5Fk,100,None,2022-05-05 22:54:27.330632+00:00
1,youtube#commentThreadListResponse,TDvBXUAZ9rIcMc4DRhJ8ZhjjG6I,UgwUR6JkxTLehh1Z3v94AaABAg,kJQP7kiw5Fk,youtube#comment,GGl8jxDeLihOojJAWR2P8jayhEk,UgwUR6JkxTLehh1Z3v94AaABAg,kJQP7kiw5Fk,Brasil,Brasil,Rafael Silva da Costa Rafa,https://yt3.ggpht.com/ytc/AKedOLQbwZJO7hunzsIA...,http://www.youtube.com/channel/UCkXq50RzrKkqGO...,UCkXq50RzrKkqGOHOA1Fjxsg,True,none,0,2022-05-05 22:45:35+00:00,2022-05-05 22:45:35+00:00,True,0,True,QURTSl9pM2ctV1F1VHV2dmJ0VUtrbHdIWG5PVUJjeHVkNk...,90,100,snippet,kJQP7kiw5Fk,100,None,2022-05-05 22:54:27.330632+00:00
2,youtube#commentThreadListResponse,TDvBXUAZ9rIcMc4DRhJ8ZhjjG6I,UgxF3IiHQP5NuWjvHGd4AaABAg,kJQP7kiw5Fk,youtube#comment,k3fJbb79_VRctuWHKJTl4ubkAOg,UgxF3IiHQP5NuWjvHGd4AaABAg,kJQP7kiw5Fk,Szeretlek💋💋,Szeretlek💋💋,Renàta Németh,https://yt3.ggpht.com/ytc/AKedOLRZHIxt5TPwc2ol...,http://www.youtube.com/channel/UC310yReVLuaLKt...,UC310yReVLuaLKtizh-aRwcQ,True,none,0,2022-05-05 22:39:34+00:00,2022-05-05 22:39:43+00:00,True,0,True,QURTSl9pM2ctV1F1VHV2dmJ0VUtrbHdIWG5PVUJjeHVkNk...,90,100,snippet,kJQP7kiw5Fk,100,None,2022-05-05 22:54:27.330632+00:00

In [ ]:
comment_thrd_vid['snippet.topLevelComment.snippet.publishedAt'].max() - comment_thrd_vid['snippet.topLevelComment.snippet.publishedAt'].min()

Timedelta('0 days 02:57:56')

In [ ]:
comment_thrd_vid.filter(regex='authorDisplay|textOriginal|likeCount|publishedAt')

,snippet.topLevelComment.snippet.textOriginal,snippet.topLevelComment.snippet.authorDisplayName,snippet.topLevelComment.snippet.likeCount,snippet.topLevelComment.snippet.publishedAt
0,💋💋💋💋💋💋,Renàta Németh,0,2022-05-05 22:49:25+00:00
1,Brasil,Rafael Silva da Costa Rafa,0,2022-05-05 22:45:35+00:00
2,Szeretlek💋💋,Renàta Németh,0,2022-05-05 22:39:34+00:00
3,Èletemmm,Renàta Németh,0,2022-05-05 22:38:39+00:00
4,Ajh màr,Renàta Németh,0,2022-05-05 22:38:31+00:00
...,...,...,...,...
85,People r gaining subs by their legendary comm...,GLOCK YT,1,2022-05-05 19:57:16+00:00
86,Roby Nem szeretem őt\nNem mutatok semmmitt s...,Renàta Németh,1,2022-05-05 19:55:31+00:00
87,Mindent meg beszèltünk!!!!!!!,Renàta Németh,1,2022-05-05 19:53:39+00:00
88,https://youtu.be/2c_HwbreurE,SS Creation,2,2022-05-05 19:51:52+00:00
89,Mindent megbeszéltünk nem?,Renàta Németh,1,2022-05-05 19:51:29+00:00

In [ ]:
(comment_thrd_vid
 .groupby('snippet.topLevelComment.snippet.authorDisplayName')
 .agg({'snippet.topLevelComment.snippet.likeCount': ['sum', 'count']})
 .sort_values(('snippet.topLevelComment.snippet.likeCount','sum'), ascending=False))

                                                  snippet.topLevelComment.snippet.likeCount  \
                                                                                        sum
snippet.topLevelComment.snippet.authorDisplayName
JOHNNY K ASTEROID                                                                        36
Renàta Németh                                                                             4
SS Creation                                                                               2
RanKs_Sensei                                                                              2
Ken Masonj                                                                                2
Tatakae                                                                                   1
Zero_Play                                                                                 1
K&M Fish Cutting                                                                          1
#Dynamo                                                                                   1
GLOCK YT                                                                                  1
ĶHADAR ZƏED                                                                               1
brayan YT                                                                                 1
Simplicity Tween Spa                                                                      0
invasive                                                                                  0
bobrossthereal                                                                            0
thereal_AGC                                                                               0
Yoyo Uwu                                                                                  0
YIKIKMAN FC                                                                               0
Sonrisa                                                                                   0
شنوي اسكوبر                                                                               0
종초진                                                                                       0
Rafael Silva da Costa Rafa                                                                0
Andreina Suarez                                                                           0
Promotion Man                                                                             0
PRO STARS                                                                                 0
Lizzet Qz                                                                                 0
Lamia Lamo                                                                                0
Kevin Eduardo Timaná Ordinola                                                             0
Katie                                                                                     0
Flux Fakiey                                                                               0
FilmBu                                                                                    0
Ercan Özkan                                                                               0
DuX gaming                                                                                0
Blue tech                                                                                 0
🌼ɢʜᴏsᴛ🌼                                                                                   0


                                                  count
snippet.topLevelComment.snippet.authorDisplayName
JOHNNY K ASTEROID                                    36
Renàta Németh                                        13
SS Creation                                           1
RanKs_Sensei                                          2
Ken Masonj                                            1
Tatakae                                               1
Zero_Play                                             1
K&M Fish Cutting                                      1
#Dynamo                                               1
GLOCK YT                                              1
ĶHADAR ZƏED                                           1
brayan YT                                             1
Simplicity Tween Spa                                  2
invasive                                              1
bobrossthereal                                        1
thereal_AGC                                           1
Yoyo Uwu                                              1
YIKIKMAN FC                                           1
Sonrisa                                               1
شنوي اسكوبر                                           2
종초진                                                   5
Rafael Silva da Costa Rafa                            1
Andreina Suarez                                       1
Promotion Man                                         1
PRO STARS                                             1
Lizzet Qz                                             1
Lamia Lamo                                            2
Kevin Eduardo Timaná Ordinola                         1
Katie                                                 1
Flux Fakiey                                           1
FilmBu                                                1
Ercan Özkan                                           1
DuX gaming                                            1
Blue tech                                             1
🌼ɢʜᴏsᴛ🌼                                               1

In [ ]:
comment_thrd_vid['id'][:10]

0    UgzKkFDLaMSNZ2IED6J4AaABAg
1    UgwUR6JkxTLehh1Z3v94AaABAg
2    UgxF3IiHQP5NuWjvHGd4AaABAg
3    Ugwah00trPAAxD5Yi554AaABAg
4    Ugx7EqO9WXh-sTLZ-CJ4AaABAg
5    UgwQ8oTNWm-d2QI9o994AaABAg
6    UgwBd-tfx5z5utL2_JB4AaABAg
7    Ugw8e3W-fPhJqOaafxt4AaABAg
8    Ugz_idKO7OCiCusoI2h4AaABAg
9    Ugw5QqsJbt00wO4YcNR4AaABAg
Name: id, dtype: object

In [ ]:
despacito = adv.youtube.videos_list(key=key, part='contentDetails,snippet,statistics', id='kJQP7kiw5Fk')

In [ ]:
despacito

,kind,etag,id,snippet.publishedAt,snippet.channelId,snippet.title,snippet.description,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,snippet.thumbnails.medium.url,snippet.thumbnails.medium.width,snippet.thumbnails.medium.height,snippet.thumbnails.high.url,snippet.thumbnails.high.width,snippet.thumbnails.high.height,snippet.thumbnails.standard.url,snippet.thumbnails.standard.width,snippet.thumbnails.standard.height,snippet.thumbnails.maxres.url,snippet.thumbnails.maxres.width,snippet.thumbnails.maxres.height,snippet.channelTitle,snippet.tags,snippet.categoryId,snippet.liveBroadcastContent,snippet.localized.title,snippet.localized.description,snippet.defaultAudioLanguage,contentDetails.duration,contentDetails.dimension,contentDetails.definition,contentDetails.caption,contentDetails.licensedContent,contentDetails.projection,statistics.viewCount,statistics.likeCount,statistics.favoriteCount,statistics.commentCount,totalResults,resultsPerPage,param_part,param_id,param_maxResults,param_pageToken,queryTime
0,youtube#videoListResponse,YQHq2flPbMokEaO8ed2PAPGCgtU,kJQP7kiw5Fk,2017-01-13 05:00:02+00:00,UCLp8RBhQHu9wSsq62j_Md6A,Luis Fonsi - Despacito ft. Daddy Yankee,“Despacito” disponible ya en todas las platafo...,https://i.ytimg.com/vi/kJQP7kiw5Fk/default.jpg,120,90,https://i.ytimg.com/vi/kJQP7kiw5Fk/mqdefault.jpg,320,180,https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg,480,360,https://i.ytimg.com/vi/kJQP7kiw5Fk/sddefault.jpg,640,480,https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefau...,1280,720,LuisFonsiVEVO,"[Luis, Fonsi, Despacito, UMLE, Latino, Latin, ...",10,none,Luis Fonsi - Despacito ft. Daddy Yankee,“Despacito” disponible ya en todas las platafo...,en-US,PT4M42S,2d,hd,true,True,rectangular,7831002804,48293636,0,4183587,1,1,"contentDetails,snippet,statistics",kJQP7kiw5Fk,None,None,2022-05-05 22:54:44.376330+00:00

In [ ]:
(despacito
 .filter(regex='statistics|queryTime')
 .set_index('queryTime')
 .style.format('{:,}'))

In [ ]:
today = despacito['queryTime'][0]
print('Request date:', format(today, '%b %d, %Y'))
print("Despacito was published " + str((today - despacito['snippet.publishedAt'][0]).days) + " days before this request")

Request date: May 05, 2022
Despacito was published 1938 days before this request

In [ ]:
vevo_playlists = adv.youtube.playlists_list(key=key, part='snippet,contentDetails', maxResults=200,  channelId='UC2pmfLm7iq6Ov1UwYrWYkZA')

In [ ]:
vevo_playlists['snippet.publishedAt'].max() - vevo_playlists['snippet.publishedAt'].min()

Timedelta('62 days 18:33:52')

In [ ]:
vevo_playlists.filter(regex='published|snippet\.title|description|itemCount|id$').head()

,id,snippet.publishedAt,snippet.title,snippet.description,snippet.localized.description,contentDetails.itemCount
0,PL9tY0BWXOZFtPh_BislMu1fIqPX-RmKgE,2022-05-05 14:44:41+00:00,Gryffin Videos,Check out the DJ's videos!\n\n\n\n\n\n\n\n\n\n...,Check out the DJ's videos!\n\n\n\n\n\n\n\n\n\n...,25
1,PL9tY0BWXOZFt712suGmwZdLL_ut2Rr4EP,2022-05-05 14:33:55+00:00,"New Music Friday - April 29, 2022","Tracks, lyric videos, and visualizers. Check o...","Tracks, lyric videos, and visualizers. Check o...",62
2,PL9tY0BWXOZFuu7xjz9JrzEBqG7pVBfm57,2022-05-02 15:31:41+00:00,Troy Ave 'The Sunday Service' Album,The Sunday Service' the 2022 released Christia...,The Sunday Service' the 2022 released Christia...,8
3,PL9tY0BWXOZFtF1chXQSobDYJcPVFCu1F7,2022-04-29 16:12:31+00:00,Jvck James 'ON THE ROCKS' EP,Tracks from the English R&B singer/songwriter'...,Tracks from the English R&B singer/songwriter'...,4
4,PL9tY0BWXOZFuTMr_41kd7b1f1dDtjr9NR,2022-04-29 15:08:29+00:00,Willie Nelson 'A Beautiful Time' Album,Tracks from the country legend's 2022 release....,Tracks from the country legend's 2022 release....,14

In [ ]:
vevo_playlists['contentDetails.itemCount'].value_counts().to_frame().head()

    contentDetails.itemCount
12                        16
13                        13
8                         11
6                         10
5                         10

In [ ]:
fig = go.Figure()
fig.add_bar(x=vevo_playlists['contentDetails.itemCount'].value_counts().index,
            y=vevo_playlists['contentDetails.itemCount'].value_counts().values)

fig.layout.template = 'none'
fig.layout.xaxis.title = 'Number of videos per playlist'
fig.layout.yaxis.title = 'Count of playlists'
fig

In [ ]:
(vevo_playlists
 .sort_values('contentDetails.itemCount', ascending=False)
 [['snippet.title', 'contentDetails.itemCount', 'id']])

,snippet.title,contentDetails.itemCount,id
176,2 Chainz Videos,113,PL9tY0BWXOZFv7WmrhXBgTFMbRRQHrd6ct
198,Cedarmont Kids Videos,110,PL9tY0BWXOZFsOvLUKrJHj1Dow3T6M7Ivr
132,"Vevo New Music Friday - March 18, 2022",107,PL9tY0BWXOZFvwyk5Qk60DUD1Nd3JoKLNX
29,Vevo South Africa,100,PL9tY0BWXOZFstrC9g7H_XvE_P-9NoUUZY
30,Vevo New Zealand,79,PL9tY0BWXOZFseDf5VZ3oZULlsI8nVqvTO
...,...,...,...
63,KayCyy 'TW20 50' EP,3,PL9tY0BWXOZFuW2JrAdFDUDa_IN5Vl-hZe
127,Alexis Ffrench 'Songbird' EP,3,PL9tY0BWXOZFuCjSun3p8__GOwGUdCrelW
119,Foxes 'The Kick' Album,2,PL9tY0BWXOZFuaEbZba7ly7i0zzUozk5T7
37,Tracks from Logic's 'Vinyl Days',2,PL9tY0BWXOZFvUGeDtSO93vaGKC-afEblC
150,James Blake & Endel 'Wind Down' Album,2,PL9tY0BWXOZFswLFAR-QC0dgrVyw9ZyFiW

In [ ]:
 vevo_playlist_items = adv.youtube.playlist_items_list(key=key, part='snippet', maxResults=300,
                                                      playlistId='PL9tY0BWXOZFsVNsIUCPoITIuZlzM3Y4bq')

In [ ]:
vevo_playlist_items.filter(regex='published|snippet\.(title|description)|videoId')

,snippet.publishedAt,snippet.title,snippet.description,snippet.resourceId.videoId
0,2022-04-29 14:09:21+00:00,Kris Floyd - C100EN (Official Video),Búscala en todas las plataformas: https://Kris...,BFVPemR47uo
1,2022-04-29 14:09:51+00:00,"Mariannah y Diego, Sophiv, Belu Rodriguez Kuhn...","Mariannah y Diego, Sophiv, Belu Rodriguez Kuhn...",PZ9I1hJFROQ
2,2022-04-29 14:10:21+00:00,"Jafú, Nicole Favre - Volando Bajito","Music video by Jafú, Nicole Favre performing V...",tKZFgpb6ifw
3,2022-04-29 14:10:51+00:00,YoGambii - “Fuego” (Official Music Video),YoGambii - “Fuego” Ya Disponible: \nhttps://Yo...,Y88fKR9iPiQ
4,2022-04-29 14:11:21+00:00,"Lucas Piraino, Shirel - Amazonas (Video Oficial)",Lucas Piraino & Shirel - Amazonas (Video Ofici...,od7enautix4
...,...,...,...,...
94,2022-02-11 17:06:16+00:00,Schuster & Dindi Jane 🥵 Llorando y Perreando ❤...,"Videoclip oficial de ""Llorando y Perreando"" po...",TDzQIThpzuM
95,2022-02-11 17:06:28+00:00,Saak - SUPERFUME,►Escucha “SUPERFUME” en tu plataforma preferid...,qXxyN1rpKO4
96,2022-02-11 17:06:37+00:00,Dielo - Van 4 Faltan 20 (Official Video),Escúchala en todas las plataformas:\nhttps://d...,d1xPjZmsYkk
97,2022-02-07 19:33:08+00:00,"Beéle, Blessd - Enchulao (Official Video)",Beéle - Enchulao (Official Video) ft. Blessd\n...,ITCYQf8ejXM
98,2022-02-07 19:33:20+00:00,"Omar Montes, Kevin Roldan - Bésame (Official V...","Omar Montes, Kevin Roldan - Bésame (Official V...",LDjo9MRcyFo

In [ ]:
vevo_subscriptions = adv.youtube.subscriptions_list(key=key, part='snippet,subscriberSnippet,contentDetails', 
                                                     channelId='UC2pmfLm7iq6Ov1UwYrWYkZA', maxResults=250)

In [ ]:
vevo_subscriptions.filter(regex='published|title|description|Count')

,snippet.publishedAt,snippet.title,snippet.description,contentDetails.totalItemCount,contentDetails.newItemCount,subscriberSnippet.title,subscriberSnippet.description
0,2018-04-17 01:29:25.683388+00:00,Carly Rae Jepsen,Dedicated Side B out now ❤️ http://smarturl.it...,56,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
1,2022-01-02 15:58:00.636326+00:00,French Montana,,65,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
2,2018-04-16 00:12:46.516918+00:00,SherylCrowVEVO,,110,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
3,2018-04-05 13:06:02.770449+00:00,Enrique Iglesias,This is the official YouTube channel for Enriq...,391,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
4,2013-07-29 10:40:20+00:00,VevoDSCVR,Vevo's DSCVR series alerts music fans to the m...,1032,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
...,...,...,...,...,...,...,...
244,2018-04-24 23:25:30.547848+00:00,The Cribs,Welcome to The Cribs official YouTube channel....,35,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
245,2022-01-02 16:21:36.844198+00:00,Axwell Λ Ingrosso,Axwell Λ Ingrosso are a Swedish music duo who ...,35,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
246,2018-04-07 14:12:27.787774+00:00,NBTVEVO,Nothing But Thieves on Vevo - Official Music V...,165,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
247,2015-08-24 11:43:23+00:00,LOTMVEVO,,39,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."
248,2018-04-24 23:25:30.392086+00:00,James Morrison,James Morrison's Official YouTube Channel.\nMy...,152,0,Vevo,"Vevo on YouTube - Official Music Videos, Live ..."

#Top 10 world videos

In [ ]:
 topvid = adv.youtube.videos_list(key=key,
                                           part='snippet,statistics,contentDetails,topicDetails',
                                           chart = 'mostPopular',
                                  regionCode=regions['id'].tolist(),
                                           maxResults= 10 )

In [ ]:
topvid.shape

(3210, 52)

In [ ]:
category_dict = dict(video_categories.query('param_hl == "en"')[['id', 'snippet.title']].values)
topvid['category'] = [None if pd.isna(x) else category_dict[x] for x in topvid['snippet.categoryId']]
topvid[['snippet.categoryId', 'category']].head()

  snippet.categoryId        category
0                 17          Sports
1                 17          Sports
2                 17          Sports
3                 22  People & Blogs
4                 10           Music

In [ ]:
(topvid
 .sort_values(['statistics.viewCount', 'snippet.title', 'param_regionCode'], 
              ascending=False)
 [['snippet.title', 'statistics.viewCount', 'param_regionCode']]
 .head(15))

,snippet.title,statistics.viewCount,param_regionCode
2566,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,ZA
3151,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,VN
3175,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,TW
2740,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,SV
3055,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,SK
2530,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,SG
3090,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,SE
3011,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,PT
2792,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,PH
2520,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,NZ
2975,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,NP
2963,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,NO
2986,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,NL
2951,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,MY
2912,PSY - 'That That (prod. & feat. SUGA of BTS)' MV,93519898,LU

In [ ]:
topvid['snippet.title'].value_counts().to_frame()[:10]

                                                    snippet.title
PSY - 'That That (prod. & feat. SUGA of BTS)' MV               81
BTS (방탄소년단) ‘Proof’ Logo Trailer                               81
REAL MADRID 3-1 MANCHESTER CITY **LOCURA EN EL ...             57
Spider-Man: No Way Home | #TeLoResumo                          51
REACCIONANDO AL REAL MADRID VS MANCHESTER CITY ...             48
HINCHAS del BARÇA REACCIONAN al REAL MADRID 3-1...             42
Obi-Wan Kenobi | Official Trailer | Disney+                    42
ريال مدريد ومانشستر سيتي 1:3 - تاااني يا ريال م...             42
CRAZY Real Madrid DRESSING ROOM after reaching ...             39
LAST TO TALK WINS $10,000                                      39

In [ ]:
'errors' in topvid # a column named "errors" would be in the dataset if we had any

False

In [ ]:
topvid['snippet.title'].isna().sum()

0

In [ ]:
topvid[topvid['snippet.title'].isna()]

Empty DataFrame
Columns: [kind, etag, id, snippet.publishedAt, snippet.channelId, snippet.title, snippet.description, snippet.thumbnails.default.url, snippet.thumbnails.default.width, snippet.thumbnails.default.height, snippet.thumbnails.medium.url, snippet.thumbnails.medium.width, snippet.thumbnails.medium.height, snippet.thumbnails.high.url, snippet.thumbnails.high.width, snippet.thumbnails.high.height, snippet.channelTitle, snippet.tags, snippet.categoryId, snippet.liveBroadcastContent, snippet.localized.title, snippet.localized.description, contentDetails.duration, contentDetails.dimension, contentDetails.definition, contentDetails.caption, contentDetails.licensedContent, contentDetails.projection, statistics.viewCount, statistics.likeCount, statistics.favoriteCount, statistics.commentCount, topicDetails.topicCategories, contentDetails.regionRestriction.allowed, snippet.thumbnails.standard.url, snippet.thumbnails.standard.width, snippet.thumbnails.standard.height, snippet.thumbnails.maxres.url, snippet.thumbnails.maxres.width, snippet.thumbnails.maxres.height, snippet.defaultAudioLanguage, snippet.defaultLanguage, nextPageToken, totalResults, resultsPerPage, param_part, param_chart, param_maxResults, param_regionCode, param_pageToken, queryTime, contentDetails.regionRestriction.blocked, category]
Index: []

In [ ]:
(topvid
 .query('param_regionCode=="BR"')
 .dropna(subset=['statistics.viewCount'])
 .sort_values('statistics.viewCount', ascending=False)
 [['snippet.title', 'statistics.viewCount']]
 .style.format({'statistics.viewCount': '{:,}'}))

In [ ]:
(topvid
 .query('param_regionCode=="FR"')
 .dropna(subset=['statistics.viewCount'])
 .sort_values('statistics.viewCount', ascending=False)
 [['snippet.title', 'statistics.viewCount']]
 .style.format({'statistics.viewCount': '{:,}'}))

In [ ]:
(topvid
 .dropna(subset=['statistics.viewCount'])
 .sort_values(['param_regionCode', 'statistics.viewCount'],
              ascending=[True, False])
 .groupby('param_regionCode', as_index=False)
 .head(3)
 [['param_regionCode', 'snippet.title',  'statistics.viewCount']][:15]
 .style.format({'statistics.viewCount': '{:,}'}))

In [ ]:
category_sum_count = (topvid
                      .drop_duplicates(subset=['snippet.title'])
                      .dropna(subset=['statistics.viewCount'])
                      .groupby('category')
                      .agg({'statistics.viewCount': ['count', 'sum']})
                      ['statistics.viewCount']
                      .sort_values('sum', ascending=False))
category_sum_count.style.format({'sum': '{:,}'})

In [ ]:
fig = go.Figure()
labels = (category_sum_count.index.astype(str) + ' (' + category_sum_count['count'].astype(str) + ' videos)').values
fig.add_treemap(labels=labels, 
                parents=['All Categories' for i in range(len(category_sum_count))], 
                values=category_sum_count['sum'],
                texttemplate='<b>%{label}</b><br><br>Total views: %{value}<br>%{percentParent} of total')
fig.layout.template = 'none'
fig.layout.height = 600
fig.layout.title = 'Total views by cateogry of video'
fig

In [ ]:
(topvid
 .drop_duplicates(subset=['id'])
 .dropna(subset=['id'])
 .assign(video_age_days=lambda df: df['queryTime'].sub(df['snippet.publishedAt']).dt.days)
 .groupby('video_age_days', as_index=False)
 ['statistics.viewCount'].sum()
 .sort_values('statistics.viewCount', ascending=False)
 .reset_index(drop=True)
 .head(10)
 .assign(perc=lambda df: df['statistics.viewCount'].div(df['statistics.viewCount'].sum()).round(2))
 .assign(cum_perc=lambda df: df['perc'].cumsum())
 .style.format({'statistics.viewCount': '{:,}', 'perc': '{:.1%}', 'cum_perc': '{:.1%}'}))

In [ ]:
topvid['video_age_days'] = topvid['queryTime'].sub(topvid['snippet.publishedAt']).dt.days
df = topvid.dropna(subset=['snippet.title']).drop_duplicates('snippet.title')
fig = go.Figure()
fig.add_histogram(x=df['video_age_days'], nbinsx=22)
fig.layout.bargap = 0.1
fig.layout.template = 'none'
fig.layout.title = 'Video age in days'
fig.layout.xaxis.title = 'Age in days'
fig.layout.yaxis.title = 'Number of videos'
fig

In [ ]:
tags_stats_cats = (topvid
                   .drop_duplicates(subset=['snippet.title'])
                   .dropna(subset=['statistics.viewCount'])
                   [['snippet.tags', 'statistics.viewCount', 'category']]
                   .reset_index(drop=True))
tags_stats_cats.head()

,snippet.tags,statistics.viewCount,category
0,"[bt sport, football, soccer, sport, champions ...",2499154,Sports
1,"[bt sport, football, soccer, sport, champions ...",2437851,Sports
2,"[real madrid, manchester city, champions leagu...",969121,Sports
3,NaN,2865477,People & Blogs
4,"[7sain Aljassmi, 7ussain aljassmi, Al Jassmi, ...",3802773,Music

In [ ]:
from collections import defaultdict
dd = defaultdict(lambda: ['', 0])


for i, tag_list in enumerate(tags_stats_cats['snippet.tags']):
    if isinstance(tag_list, list):
        for tag in tag_list:
                dd[tag][0] = tags_stats_cats['category'][i]
                dd[tag][1] += tags_stats_cats['statistics.viewCount'][i]
    else:
        if pd.isna(tag_list):
            dd[None][0] = tags_stats_cats['category'][i]
            dd[None][1] += tags_stats_cats['statistics.viewCount'][i]      

by_tag_category = (pd.DataFrame(list(zip(dd.keys(), dd.values()))).assign(category=lambda df: df[1].str[0],
                                                       view_count=lambda df: df[1].str[1]).drop(columns=[1])
                  .sort_values('view_count', ascending=False)
                  .rename(columns={0: 'tag'})
                  .reset_index(drop=True))
               
by_tag_category.head(10).style.format({'view_count': '{:,}'})